// <auto-generated />
using System;
using JeverlyStore.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JeverlyStore.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241205193332_Init2")]
    partial class Init2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JeverlyStroe.Domain.ModelsDb.CategoriesDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("createdAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PathImg")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pathImg");

                    b.HasKey("Id");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("JeverlyStroe.Domain.ModelsDb.ComplaintDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("IdOrders")
                        .HasColumnType("uuid")
                        .HasColumnName("idOrders");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("uuid")
                        .HasColumnName("idUser");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("complaints");
                });

            modelBuilder.Entity("JeverlyStroe.Domain.ModelsDb.OrderDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("Cost")
                        .HasColumnType("double precision")
                        .HasColumnName("cost");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("createdAt");

                    b.Property<Guid>("IdProduct")
                        .HasColumnType("uuid")
                        .HasColumnName("idProduct");

                    b.Property<Guid>("IdRequest")
                        .HasColumnType("uuid")
                        .HasColumnName("idRequest");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("uuid")
                        .HasColumnName("idUser");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.HasIndex("UserId");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("JeverlyStroe.Domain.ModelsDb.PicturesProductDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("IdProduct")
                        .HasColumnType("uuid")
                        .HasColumnName("idProduct");

                    b.Property<string>("PathImg")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pathImg");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("pictures_product");
                });

            modelBuilder.Entity("JeverlyStroe.Domain.ModelsDb.ProductDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CategoriesDbId")
                        .HasColumnType("uuid");

                    b.Property<double>("Cost")
                        .HasColumnType("double precision")
                        .HasColumnName("cost");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("createdAt");

                    b.Property<Guid>("IdCategories")
                        .HasColumnType("uuid")
                        .HasColumnName("idCategories");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("OrderDbId")
                        .HasColumnType("uuid");

                    b.Property<string>("PathImage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pathImg");

                    b.HasKey("Id");

                    b.HasIndex("CategoriesDbId");

                    b.HasIndex("OrderDbId");

                    b.ToTable("products");
                });

            modelBuilder.Entity("JeverlyStroe.Domain.ModelsDb.RequestDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("createdAt");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("IdOrder")
                        .HasColumnType("uuid")
                        .HasColumnName("idOrder");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("uuid")
                        .HasColumnName("idUser");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("requests");
                });

            modelBuilder.Entity("JeverlyStroe.Domain.ModelsDb.UserDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("createdAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("login");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("PathImage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pathImage");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("JeverlyStroe.Domain.ModelsDb.ComplaintDb", b =>
                {
                    b.HasOne("JeverlyStroe.Domain.ModelsDb.OrderDb", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JeverlyStroe.Domain.ModelsDb.UserDb", "User")
                        .WithMany("Complaints")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JeverlyStroe.Domain.ModelsDb.OrderDb", b =>
                {
                    b.HasOne("JeverlyStroe.Domain.ModelsDb.RequestDb", "Request")
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JeverlyStroe.Domain.ModelsDb.UserDb", "User")
                        .WithMany("Order")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JeverlyStroe.Domain.ModelsDb.PicturesProductDb", b =>
                {
                    b.HasOne("JeverlyStroe.Domain.ModelsDb.ProductDb", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("JeverlyStroe.Domain.ModelsDb.ProductDb", b =>
                {
                    b.HasOne("JeverlyStroe.Domain.ModelsDb.CategoriesDb", null)
                        .WithMany("Products")
                        .HasForeignKey("CategoriesDbId");

                    b.HasOne("JeverlyStroe.Domain.ModelsDb.OrderDb", null)
                        .WithMany("Product")
                        .HasForeignKey("OrderDbId");
                });

            modelBuilder.Entity("JeverlyStroe.Domain.ModelsDb.RequestDb", b =>
                {
                    b.HasOne("JeverlyStroe.Domain.ModelsDb.UserDb", "User")
                        .WithMany("Request")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("JeverlyStroe.Domain.ModelsDb.CategoriesDb", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("JeverlyStroe.Domain.ModelsDb.OrderDb", b =>
                {
                    b.Navigation("Product");
                });

            modelBuilder.Entity("JeverlyStroe.Domain.ModelsDb.UserDb", b =>
                {
                    b.Navigation("Complaints");

                    b.Navigation("Order");

                    b.Navigation("Request");
                });
#pragma warning restore 612, 618
        }
    }
}
